# 开发环境配置
spring:
        profiles: dev
        redis:
                host: 192.168.6.43
                port: 6379
                password: 1234qwer
                database: 5
han:
        mqtt:
                http-api:
                        http-enable: false
                        send-auth: http://192.168.6.44:8080/api/auth #返回true /false
                        send-sub-topic:  http://localhost:8080/aaa?jsonbody #返回true /false
                        send-msg:  http://localhost:8080/cc?jsonbody  #无需返回
                        send-state:  http://localhost:8080/dd?jsonbody  #无需返回
                broker:
                        cache-type: redis
                        ssl-enable: false # 默认不开启ssl认证
                        ws-enable: false
                        # broker唯一标识
                        id: mqtt-broker-1
                        # SSL端口
                        ssl-port: 1883
                        # SSL密钥文件密码
                        ssl-password: 123456
                        # websocket端口
                        websocket-ssl-port: 9995
                        # websocket path 值
                        websocket-path: /mqtt
                        # 心跳时间(秒)
                        keep-alive: 60
                        # 开启Epoll模式, linux下建议开启
                        use-epoll: false
                        # 开启组播方式集群
                        enable-multicast-group: true
                        # 组播地址
                        multicast-group: 239.255.255.255

                        cache:
                                # 持久化缓存内存初始化大小(MB)
                                persistence-initial-size: 64
                                # 持久化缓存占用内存最大值(MB)
                                persistence-max-size: 128
                                # 非持久化缓存内存初始化大小(MB)
                                not-persistence-initial-size: 64
                                # 非持久化缓存占用内存最大值(MB)
                                not-persistence-max-size: 128
logging:
        level:
                root: info
                cn.recallcode.iot.mqtt.server: debug

